### ISSUE TITLE
OMJulia scripting api docu: No explanations

### ISSUE THREAD

**Issue by olivleno** [OpenModelica/OMJulia.jl#86] opened 2023-08-22 13:11 UTC
The [scripting API](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html) is basically a listing of the syntax of the available functions. 
This might be ok, if you're asking: "How to use it?", but it is not very helpful if you asking: "What is it good for?".

For instance, when searching for "directorypath" you find get functions for: WorkingDirectory, HomeDirectory, TempDirectory und InstallationDirectory, but there is no notion of what the difference is.

It would be great to have at least on sentence explaining the purpose of the functions.

**Comment by AnHeuermann** [comment] 2023-08-22 13:26
Duplicate of OpenModelica bug: https://github.com/OpenModelica/OpenModelica/issues/11033

**Closed by AnHeuermann** 2023-08-22 13:26 UTC
